/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten
// Please do not edit this file manually. All changes will be lost
// import { GraphQLResolveInfo } from "graphql";
